name: Lint and Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # setup pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      # setup cache
      - name: Get pnpm store directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm
      # setup project
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      # check types
      - name: Check types
        run: |
          pnpm run type-check
      # lint
      - name: Lint
        run: |
          pnpm run lint
      # test
      - name: Run tests
        run: |
          pnpm test
